### ISSUE TITLE
Install on Windows fails with toolset error

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/hub.js#539]
Installing a fresh clone of the repo fails with Microsoft products. My computer has Visual Studio 2017 as well as
* VC++ 2017 version 15.9 v14.16 latest v141 tools
* VC++ 2015.3 version 14.00 (v140) toolset for desktop (added to see if it was needed despite the "v141" text)
* MSBuild

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 06/08/2021 16:11:48.
Project "C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\binding.sln" (1) is building "C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default
targets).
Project "C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (
default targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141
 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v141 to build using the v141 build tools. [C:\Users\mike6491\ag\hub.js\node_mo
dules\node-sass\build\src\libsass.vcxproj]
Done Building Project "C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.


Build FAILED.

"C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"C:\Users\mike6491\ag\hub.js\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
(PlatformPrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v1
41 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v141 to build using the v141 build tools. [C:\Users\mike6491\ag\hub.js\node_
modules\node-sass\build\src\libsass.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.86
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mike6491\ag\hub.js\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\mike6491\\AppData\\Local\\Volta\\tools\\image\\node\\14.16.0\\node.exe" "C:\\Users\\mike6491\\ag\\hub.js\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\mike6491\ag\hub.js\node_modules\node-sass
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
```

**Comment by dbouwman** [comment]
@MikeTschudi - verified on a VM... I will look into removing node-sass or doing something so that it does not require a "build"
